[project]
name = "olt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "narang99", email = "hariom2711@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "scikit-learn<1.6",
    "boto3>=1.43.30",
    "captum>=0.9.0",
    "cloudpathlib>=0.24.0",
    "hdbscan==0.8.39",
    "huggingface-hub>=1.19.0",
    "matplotlib>=3.11.0",
    "numpy==2.0",
    "pandas==2.2.2",
    "pillow>=12.2.0",
    "torch>=2.11",
    "torch-lucent>=0.1.8",
    "torchvision>=0.27.0",
    "tqdm>=4.68.2",
    "webdataset>=1.0.2",
    "seaborn>=0.13.2",
]

[project.scripts]
olt = "olt:main"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "ruff>=0.15.20",
]
