# Generated by Django 6.0.4 on 2026-05-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('data_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='neural_data.model')),
            ],
            options={
                'db_table': 'inputs',
                'unique_together': {('model', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('layer_type', models.CharField(max_length=100)),
                ('coordinate_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='neural_data.input')),
            ],
            options={
                'db_table': 'activations',
                'unique_together': {('input', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='SaliencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saliency_maps', to='neural_data.input')),
            ],
            options={
                'db_table': 'saliency_maps',
                'unique_together': {('input', 'coordinate')},
            },
        ),
    ]
