# Generated by Django 6.0.4 on 2026-05-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('definition', models.JSONField()),
                ('pt_file', models.FileField(upload_to='models/pt/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('data_path', models.CharField(max_length=500)),
                ('pt_file', models.FileField(upload_to='inputs/pt/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='neural_data.model')),
            ],
            options={
                'db_table': 'inputs',
                'unique_together': {('model', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('layer_name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('layer_type', models.CharField(max_length=100)),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('output_channel', models.IntegerField(blank=True, null=True)),
                ('input_channel', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='neural_data.model')),
            ],
            options={
                'db_table': 'weights',
                'unique_together': {('model', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='neural_data.input')),
            ],
            options={
                'db_table': 'works',
                'unique_together': {('input', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='neural_data.work')),
            ],
            options={
                'db_table': 'work_graphs',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('layer_name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('layer_type', models.CharField(max_length=100)),
                ('coordinate_type', models.CharField(max_length=100)),
                ('output_channel', models.IntegerField(blank=True, null=True)),
                ('input_channel', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='neural_data.input')),
            ],
            options={
                'db_table': 'activations',
                'unique_together': {('input', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='SaliencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('output_channel', models.IntegerField(blank=True, null=True)),
                ('input_channel', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saliency_maps', to='neural_data.input')),
            ],
            options={
                'db_table': 'saliency_maps',
                'unique_together': {('input', 'coordinate')},
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('note', models.TextField()),
                ('label', models.CharField(max_length=20)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.weight')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.work')),
            ],
            options={
                'db_table': 'pois',
                'unique_together': {('work', 'weight', 'x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='TempPruneSaliencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('output_channel', models.IntegerField(blank=True, null=True)),
                ('input_channel', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('is_modified', models.BooleanField(default=False)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_saliency_maps', to='neural_data.input')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.workgraph')),
            ],
            options={
                'unique_together': {('input', 'coordinate', 'graph')},
            },
        ),
        migrations.CreateModel(
            name='WorkSaliencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('output_channel', models.IntegerField(blank=True, null=True)),
                ('input_channel', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.workgraph')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_saliency_maps', to='neural_data.input')),
            ],
            options={
                'unique_together': {('input', 'coordinate', 'graph')},
            },
        ),
    ]
