# Generated by Django 6.0.4 on 2026-05-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neural_data.weight')),
            ],
            options={
                'db_table': 'kernel_labels',
            },
        ),
    ]
