# Generated by Django 6.0.4 on 2026-05-01 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('layer_type', models.CharField(max_length=100)),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='neural_data.model')),
            ],
            options={
                'db_table': 'weights',
                'unique_together': {('model', 'coordinate')},
            },
        ),
    ]
