# Generated by Django 6.0.4 on 2026-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0002_kernellabels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worksaliencymap',
            unique_together={('coordinate', 'graph')},
        ),
        migrations.AddField(
            model_name='worksaliencymap',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
