# Generated by Django 6.0.4 on 2026-05-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0002_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='neural_data.input')),
            ],
            options={
                'db_table': 'works',
                'unique_together': {('input', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LayerThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(db_index=True, max_length=200)),
                ('slider_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='neural_data.model')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='neural_data.work')),
            ],
            options={
                'db_table': 'layer_thresholds',
                'unique_together': {('work', 'model', 'layer_id')},
            },
        ),
    ]
