# Generated by Django 6.0.4 on 2026-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0003_work_layerthreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerthreshold',
            name='slider_value',
        ),
        migrations.AddField(
            model_name='layerthreshold',
            name='algorithm',
            field=models.JSONField(default=dict),
        ),
    ]
