# Generated by Django 6.0.4 on 2026-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0003_alter_worksaliencymap_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_coordinate', models.CharField(db_index=True, max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kernel_notes',
            },
        ),
    ]
