# Generated by Django 6.0.4 on 2026-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0004_remove_layerthreshold_slider_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerthreshold',
            name='slider_value',
            field=models.FloatField(default=100.0),
        ),
    ]
