# Generated by Django 6.0.4 on 2026-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0004_kernelnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='larger_pattern',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
