# Generated by Django 6.0.4 on 2026-05-03 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0005_layerthreshold_slider_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.work')),
            ],
            options={
                'unique_together': {('work', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='WorkSaliencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('shape', models.JSONField()),
                ('coordinate_type', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinate', models.CharField(db_index=True, max_length=200)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.workgraph')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_saliency_maps', to='neural_data.input')),
            ],
            options={
                'unique_together': {('input', 'coordinate', 'graph')},
            },
        ),
    ]
