# Generated by Django 6.0.4 on 2026-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0005_poi_larger_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernellabels',
            name='larger_patterns',
            field=models.JSONField(default=list),
        ),
    ]
