# Generated by Django 6.0.4 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0006_workgraph_worksaliencymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='saliencymap',
            name='layer_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worksaliencymap',
            name='layer_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
