# Generated by Django 6.0.4 on 2026-05-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0006_kernellabels_larger_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='neural_data.work')),
            ],
            options={
                'db_table': 'pinned_works',
            },
        ),
    ]
