# Generated by Django 6.0.4 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0007_pinnedwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksaliencymap',
            name='slice_state',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('skip', 'Skip'), ('review', 'Review'), ('done', 'Done')], db_index=True, default='not_done', max_length=20),
        ),
    ]
