# Generated by Django 6.0.4 on 2026-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0007_saliencymap_layer_name_worksaliencymap_layer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='layer_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='layer_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
