# Generated by Django 6.0.4 on 2026-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0008_activation_layer_name_weight_layer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='layer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='LayerThreshold',
        ),
    ]
