# Generated by Django 6.0.4 on 2026-05-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0008_worksaliencymap_slice_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksaliencymap',
            name='is_done',
        ),
    ]
