# Generated by Django 6.0.4 on 2026-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0009_remove_worksaliencymap_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='category',
            field=models.CharField(default='4', max_length=10),
            preserve_default=False,
        ),
    ]
