# Generated by Django 6.0.4 on 2026-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0009_alter_activation_layer_name_delete_layerthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saliencymap',
            name='layer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='worksaliencymap',
            name='layer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
