# Generated by Django 6.0.4 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0010_alter_saliencymap_layer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='layer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
