# Generated by Django 6.0.4 on 2026-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0012_tempprunesaliencymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempprunesaliencymap',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
