# Generated by Django 6.0.4 on 2026-05-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0013_tempprunesaliencymap_is_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='input_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='output_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saliencymap',
            name='input_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saliencymap',
            name='output_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempprunesaliencymap',
            name='input_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempprunesaliencymap',
            name='output_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='input_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='output_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksaliencymap',
            name='input_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksaliencymap',
            name='output_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
