# Generated by Django 6.0.4 on 2026-05-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0014_activation_input_channel_activation_output_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('note', models.TextField()),
                ('label', models.CharField(max_length=20)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.weight')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neural_data.work')),
            ],
            options={
                'db_table': 'pois',
                'unique_together': {('work', 'weight', 'x', 'y')},
            },
        ),
    ]
