# Generated by Django 6.0.4 on 2026-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0015_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='pt_file',
            field=models.FileField(blank=True, null=True, upload_to='inputs/pt/'),
        ),
        migrations.AddField(
            model_name='model',
            name='pt_file',
            field=models.FileField(blank=True, null=True, upload_to='models/pt/'),
        ),
    ]
