# Generated by Django 6.0.4 on 2026-05-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_data', '0016_input_pt_file_model_pt_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workgraph',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workgraph',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='neural_data.work'),
        ),
        migrations.AlterModelTable(
            name='workgraph',
            table='work_graphs',
        ),
        migrations.RemoveField(
            model_name='workgraph',
            name='alias',
        ),
    ]
